tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#003733",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#67d9c9",
        "surface-bright": "#f8f9fb",
        "on-tertiary-fixed": "#00201d",
        "secondary-fixed": "#85f6e5",
        "on-tertiary-container": "#3ca89e",
        "primary-fixed-dim": "#b0c6ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00201c",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#005048",
        "on-secondary": "#ffffff",
        "secondary-container": "#85f6e5",
        "error": "#ba1a1a",
        "surface-container": "#eceef0",
        "secondary": "#006a60",
        "on-surface-variant": "#454652",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed": "#001945",
        "outline": "#767683",
        "tertiary-fixed-dim": "#71d7cd",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#00504a",
        "surface": "#f8f9fb",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "primary-fixed": "#d9e2ff",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed": "#8ef4e9",
        "tertiary": "#00201d",
        "primary": "#001944",
        "background": "#f8f9fb",
        "on-secondary-container": "#007166",
        "on-primary-fixed-variant": "#00429c",
        "on-primary-container": "#6b95f3",
        "on-background": "#191c1e",
        "inverse-primary": "#b0c6ff",
        "on-primary": "#ffffff",
        "primary-container": "#002c6e",
        "surface-tint": "#2b5bb5",
        "outline-variant": "#c6c5d4"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
}
